export default {
    ADD_NEW_USER: 'ADD_NEW_USER',
    TOGGLE_CHAT_MODULE: 'TOGGLE_CHAT_MODULE',
    CHANGE_LANGUANGE: 'CHANGE_LANGUANGE',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    ADD_NEW_MESSAGE_STORE: 'ADD_NEW_MESSAGE',
    ADD_NEW_USER: 'ADD_NEW_USER'
}