export default {
    ADD_NEW_USER: 'ADD_NEW_USER',
    SELECTED_USER: 'SELECTED_USER',
    TOGGLE_CHAT_MODULE: 'TOGGLE_CHAT_MODULE',
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE"
}