export default {
    ADD_NEW_USER: 'ADD_NEW_USER',
    ADD_NEW_USER_STORE: 'ADD_NEW_USER_STORE',
    TOGGLE_CHAT_MODULE: 'TOGGLE_CHAT_MODULE',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    CHANGE_STATE_USER: 'CHANGE_STATE_USER',
    CHANGE_STATE_SELECTED_USER: 'CHANGE_STATE_SELECTED_USER'
}